"""initial business operating system schema

Revision ID: fa85cd14eb04
Revises: 
Create Date: 2026-06-18 00:58:55.081007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fa85cd14eb04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistantmemory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistantmemory_business_id'), 'assistantmemory', ['business_id'], unique=False)
    op.create_index(op.f('ix_assistantmemory_user_id'), 'assistantmemory', ['user_id'], unique=False)
    op.create_table('assistantmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actions_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistantmessage_business_id'), 'assistantmessage', ['business_id'], unique=False)
    op.create_index(op.f('ix_assistantmessage_thread_id'), 'assistantmessage', ['thread_id'], unique=False)
    op.create_index(op.f('ix_assistantmessage_user_id'), 'assistantmessage', ['user_id'], unique=False)
    op.create_table('assistantthread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistantthread_business_id'), 'assistantthread', ['business_id'], unique=False)
    op.create_index(op.f('ix_assistantthread_user_id'), 'assistantthread', ['user_id'], unique=False)
    op.create_table('auditevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditevent_action'), 'auditevent', ['action'], unique=False)
    op.create_index(op.f('ix_auditevent_business_id'), 'auditevent', ['business_id'], unique=False)
    op.create_index(op.f('ix_auditevent_user_id'), 'auditevent', ['user_id'], unique=False)
    op.create_table('availabilityrequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rule_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('manager_note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reviewed_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availabilityrequest_business_id'), 'availabilityrequest', ['business_id'], unique=False)
    op.create_index(op.f('ix_availabilityrequest_employee_id'), 'availabilityrequest', ['employee_id'], unique=False)
    op.create_index(op.f('ix_availabilityrequest_user_id'), 'availabilityrequest', ['user_id'], unique=False)
    op.create_table('bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bill_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('due_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('tax_cents', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('paid_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_business_id'), 'bill', ['business_id'], unique=False)
    op.create_index(op.f('ix_bill_vendor_id'), 'bill', ['vendor_id'], unique=False)
    op.create_table('billline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity_milli', sa.Integer(), nullable=False),
    sa.Column('unit_cost_cents', sa.Integer(), nullable=False),
    sa.Column('line_total_cents', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billline_account_id'), 'billline', ['account_id'], unique=False)
    op.create_index(op.f('ix_billline_bill_id'), 'billline', ['bill_id'], unique=False)
    op.create_index(op.f('ix_billline_business_id'), 'billline', ['business_id'], unique=False)
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('legal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_name'), 'business', ['name'], unique=False)
    op.create_table('businessmodule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('module_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businessmodule_business_id'), 'businessmodule', ['business_id'], unique=False)
    op.create_index(op.f('ix_businessmodule_module_key'), 'businessmodule', ['module_key'], unique=False)
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('contact_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('billing_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tax_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_business_id'), 'contact', ['business_id'], unique=False)
    op.create_index(op.f('ix_contact_name'), 'contact', ['name'], unique=False)
    op.create_table('coveragerule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('position_ids_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('departments_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('roles_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('minimum_count', sa.Integer(), nullable=False),
    sa.Column('preferred_count', sa.Integer(), nullable=False),
    sa.Column('hard_minimum', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coveragerule_business_id'), 'coveragerule', ['business_id'], unique=False)
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('min_hours_per_week', sa.Integer(), nullable=False),
    sa.Column('max_hours_per_week', sa.Integer(), nullable=False),
    sa.Column('hourly_rate_override', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_business_id'), 'employee', ['business_id'], unique=False)
    op.create_table('employeeposition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('trainee', sa.Boolean(), nullable=False),
    sa.Column('preferred', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employeeposition_business_id'), 'employeeposition', ['business_id'], unique=False)
    op.create_index(op.f('ix_employeeposition_employee_id'), 'employeeposition', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employeeposition_position_id'), 'employeeposition', ['position_id'], unique=False)
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('expense_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('payment_account_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_account_id'), 'expense', ['account_id'], unique=False)
    op.create_index(op.f('ix_expense_business_id'), 'expense', ['business_id'], unique=False)
    op.create_index(op.f('ix_expense_expense_date'), 'expense', ['expense_date'], unique=False)
    op.create_index(op.f('ix_expense_location_id'), 'expense', ['location_id'], unique=False)
    op.create_index(op.f('ix_expense_payment_account_id'), 'expense', ['payment_account_id'], unique=False)
    op.create_index(op.f('ix_expense_vendor_id'), 'expense', ['vendor_id'], unique=False)
    op.create_table('inventoryitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity_milli', sa.Integer(), nullable=False),
    sa.Column('reorder_level_milli', sa.Integer(), nullable=False),
    sa.Column('unit_cost_cents', sa.Integer(), nullable=False),
    sa.Column('sales_price_cents', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventoryitem_business_id'), 'inventoryitem', ['business_id'], unique=False)
    op.create_index(op.f('ix_inventoryitem_location_id'), 'inventoryitem', ['location_id'], unique=False)
    op.create_index(op.f('ix_inventoryitem_sku'), 'inventoryitem', ['sku'], unique=False)
    op.create_table('inventorymovement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('movement_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity_milli', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventorymovement_business_id'), 'inventorymovement', ['business_id'], unique=False)
    op.create_index(op.f('ix_inventorymovement_created_by_user_id'), 'inventorymovement', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_inventorymovement_item_id'), 'inventorymovement', ['item_id'], unique=False)
    op.create_index(op.f('ix_inventorymovement_movement_date'), 'inventorymovement', ['movement_date'], unique=False)
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issue_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('due_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('tax_cents', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('paid_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_business_id'), 'invoice', ['business_id'], unique=False)
    op.create_index(op.f('ix_invoice_customer_id'), 'invoice', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoice_number'), 'invoice', ['number'], unique=False)
    op.create_table('invoiceline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity_milli', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('tax_rate_basis_points', sa.Integer(), nullable=False),
    sa.Column('line_total_cents', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoiceline_business_id'), 'invoiceline', ['business_id'], unique=False)
    op.create_index(op.f('ix_invoiceline_invoice_id'), 'invoiceline', ['invoice_id'], unique=False)
    op.create_table('journalentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('memo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journalentry_business_id'), 'journalentry', ['business_id'], unique=False)
    op.create_index(op.f('ix_journalentry_created_by_user_id'), 'journalentry', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_journalentry_entry_date'), 'journalentry', ['entry_date'], unique=False)
    op.create_index(op.f('ix_journalentry_source_id'), 'journalentry', ['source_id'], unique=False)
    op.create_table('journalline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('debit_cents', sa.Integer(), nullable=False),
    sa.Column('credit_cents', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journalline_account_id'), 'journalline', ['account_id'], unique=False)
    op.create_index(op.f('ix_journalline_business_id'), 'journalline', ['business_id'], unique=False)
    op.create_index(op.f('ix_journalline_journal_entry_id'), 'journalline', ['journal_entry_id'], unique=False)
    op.create_table('laborprojection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('projected_sales', sa.Float(), nullable=True),
    sa.Column('labor_percent', sa.Float(), nullable=True),
    sa.Column('min_labor_percent', sa.Float(), nullable=True),
    sa.Column('max_labor_percent', sa.Float(), nullable=True),
    sa.Column('max_labor_hours', sa.Float(), nullable=True),
    sa.Column('max_labor_dollars', sa.Float(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laborprojection_business_id'), 'laborprojection', ['business_id'], unique=False)
    op.create_index(op.f('ix_laborprojection_date'), 'laborprojection', ['date'], unique=False)
    op.create_table('ledgeraccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subtype', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('system', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledgeraccount_business_id'), 'ledgeraccount', ['business_id'], unique=False)
    op.create_index(op.f('ix_ledgeraccount_code'), 'ledgeraccount', ['code'], unique=False)
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_business_id'), 'location', ['business_id'], unique=False)
    op.create_table('managersettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('store_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employee_hourly_rate', sa.Float(), nullable=False),
    sa.Column('shift_lead_hourly_rate', sa.Float(), nullable=False),
    sa.Column('gm_hourly_rate', sa.Float(), nullable=False),
    sa.Column('default_labor_percent', sa.Float(), nullable=False),
    sa.Column('min_labor_percent', sa.Float(), nullable=False),
    sa.Column('max_labor_percent', sa.Float(), nullable=False),
    sa.Column('schedule_extra_with_trainee', sa.Boolean(), nullable=False),
    sa.Column('store_open_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('store_close_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managersettings_business_id'), 'managersettings', ['business_id'], unique=False)
    op.create_table('membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_business_id'), 'membership', ['business_id'], unique=False)
    op.create_index(op.f('ix_membership_user_id'), 'membership', ['user_id'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payment_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_account_id'), 'payment', ['account_id'], unique=False)
    op.create_index(op.f('ix_payment_bill_id'), 'payment', ['bill_id'], unique=False)
    op.create_index(op.f('ix_payment_business_id'), 'payment', ['business_id'], unique=False)
    op.create_index(op.f('ix_payment_contact_id'), 'payment', ['contact_id'], unique=False)
    op.create_index(op.f('ix_payment_invoice_id'), 'payment', ['invoice_id'], unique=False)
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_business_id'), 'position', ['business_id'], unique=False)
    op.create_table('recurringavailability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurringavailability_business_id'), 'recurringavailability', ['business_id'], unique=False)
    op.create_index(op.f('ix_recurringavailability_employee_id'), 'recurringavailability', ['employee_id'], unique=False)
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_schedule_id', sa.Integer(), nullable=True),
    sa.Column('generation_scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('labor_tolerance_percent', sa.Float(), nullable=False),
    sa.Column('staffing_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_business_id'), 'schedule', ['business_id'], unique=False)
    op.create_index(op.f('ix_schedule_week_start'), 'schedule', ['week_start'], unique=False)
    op.create_table('scheduleshift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('source_rule_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduleshift_business_id'), 'scheduleshift', ['business_id'], unique=False)
    op.create_index(op.f('ix_scheduleshift_date'), 'scheduleshift', ['date'], unique=False)
    op.create_index(op.f('ix_scheduleshift_schedule_id'), 'scheduleshift', ['schedule_id'], unique=False)
    op.create_table('schedulewarning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedulewarning_business_id'), 'schedulewarning', ['business_id'], unique=False)
    op.create_index(op.f('ix_schedulewarning_schedule_id'), 'schedulewarning', ['schedule_id'], unique=False)
    op.create_table('taskitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('due_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taskitem_assigned_user_id'), 'taskitem', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_taskitem_business_id'), 'taskitem', ['business_id'], unique=False)
    op.create_index(op.f('ix_taskitem_created_by_user_id'), 'taskitem', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_taskitem_location_id'), 'taskitem', ['location_id'], unique=False)
    op.create_table('temporaryunavailability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temporaryunavailability_business_id'), 'temporaryunavailability', ['business_id'], unique=False)
    op.create_index(op.f('ix_temporaryunavailability_employee_id'), 'temporaryunavailability', ['employee_id'], unique=False)
    op.create_table('useraccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_useraccount_employee_id'), 'useraccount', ['employee_id'], unique=False)
    op.create_index(op.f('ix_useraccount_username'), 'useraccount', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_useraccount_username'), table_name='useraccount')
    op.drop_index(op.f('ix_useraccount_employee_id'), table_name='useraccount')
    op.drop_table('useraccount')
    op.drop_index(op.f('ix_temporaryunavailability_employee_id'), table_name='temporaryunavailability')
    op.drop_index(op.f('ix_temporaryunavailability_business_id'), table_name='temporaryunavailability')
    op.drop_table('temporaryunavailability')
    op.drop_index(op.f('ix_taskitem_location_id'), table_name='taskitem')
    op.drop_index(op.f('ix_taskitem_created_by_user_id'), table_name='taskitem')
    op.drop_index(op.f('ix_taskitem_business_id'), table_name='taskitem')
    op.drop_index(op.f('ix_taskitem_assigned_user_id'), table_name='taskitem')
    op.drop_table('taskitem')
    op.drop_index(op.f('ix_schedulewarning_schedule_id'), table_name='schedulewarning')
    op.drop_index(op.f('ix_schedulewarning_business_id'), table_name='schedulewarning')
    op.drop_table('schedulewarning')
    op.drop_index(op.f('ix_scheduleshift_schedule_id'), table_name='scheduleshift')
    op.drop_index(op.f('ix_scheduleshift_date'), table_name='scheduleshift')
    op.drop_index(op.f('ix_scheduleshift_business_id'), table_name='scheduleshift')
    op.drop_table('scheduleshift')
    op.drop_index(op.f('ix_schedule_week_start'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_business_id'), table_name='schedule')
    op.drop_table('schedule')
    op.drop_index(op.f('ix_recurringavailability_employee_id'), table_name='recurringavailability')
    op.drop_index(op.f('ix_recurringavailability_business_id'), table_name='recurringavailability')
    op.drop_table('recurringavailability')
    op.drop_index(op.f('ix_position_business_id'), table_name='position')
    op.drop_table('position')
    op.drop_index(op.f('ix_payment_invoice_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_contact_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_business_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_bill_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_account_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_membership_user_id'), table_name='membership')
    op.drop_index(op.f('ix_membership_business_id'), table_name='membership')
    op.drop_table('membership')
    op.drop_index(op.f('ix_managersettings_business_id'), table_name='managersettings')
    op.drop_table('managersettings')
    op.drop_index(op.f('ix_location_business_id'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_ledgeraccount_code'), table_name='ledgeraccount')
    op.drop_index(op.f('ix_ledgeraccount_business_id'), table_name='ledgeraccount')
    op.drop_table('ledgeraccount')
    op.drop_index(op.f('ix_laborprojection_date'), table_name='laborprojection')
    op.drop_index(op.f('ix_laborprojection_business_id'), table_name='laborprojection')
    op.drop_table('laborprojection')
    op.drop_index(op.f('ix_journalline_journal_entry_id'), table_name='journalline')
    op.drop_index(op.f('ix_journalline_business_id'), table_name='journalline')
    op.drop_index(op.f('ix_journalline_account_id'), table_name='journalline')
    op.drop_table('journalline')
    op.drop_index(op.f('ix_journalentry_source_id'), table_name='journalentry')
    op.drop_index(op.f('ix_journalentry_entry_date'), table_name='journalentry')
    op.drop_index(op.f('ix_journalentry_created_by_user_id'), table_name='journalentry')
    op.drop_index(op.f('ix_journalentry_business_id'), table_name='journalentry')
    op.drop_table('journalentry')
    op.drop_index(op.f('ix_invoiceline_invoice_id'), table_name='invoiceline')
    op.drop_index(op.f('ix_invoiceline_business_id'), table_name='invoiceline')
    op.drop_table('invoiceline')
    op.drop_index(op.f('ix_invoice_number'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_customer_id'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_business_id'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_inventorymovement_movement_date'), table_name='inventorymovement')
    op.drop_index(op.f('ix_inventorymovement_item_id'), table_name='inventorymovement')
    op.drop_index(op.f('ix_inventorymovement_created_by_user_id'), table_name='inventorymovement')
    op.drop_index(op.f('ix_inventorymovement_business_id'), table_name='inventorymovement')
    op.drop_table('inventorymovement')
    op.drop_index(op.f('ix_inventoryitem_sku'), table_name='inventoryitem')
    op.drop_index(op.f('ix_inventoryitem_location_id'), table_name='inventoryitem')
    op.drop_index(op.f('ix_inventoryitem_business_id'), table_name='inventoryitem')
    op.drop_table('inventoryitem')
    op.drop_index(op.f('ix_expense_vendor_id'), table_name='expense')
    op.drop_index(op.f('ix_expense_payment_account_id'), table_name='expense')
    op.drop_index(op.f('ix_expense_location_id'), table_name='expense')
    op.drop_index(op.f('ix_expense_expense_date'), table_name='expense')
    op.drop_index(op.f('ix_expense_business_id'), table_name='expense')
    op.drop_index(op.f('ix_expense_account_id'), table_name='expense')
    op.drop_table('expense')
    op.drop_index(op.f('ix_employeeposition_position_id'), table_name='employeeposition')
    op.drop_index(op.f('ix_employeeposition_employee_id'), table_name='employeeposition')
    op.drop_index(op.f('ix_employeeposition_business_id'), table_name='employeeposition')
    op.drop_table('employeeposition')
    op.drop_index(op.f('ix_employee_business_id'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_coveragerule_business_id'), table_name='coveragerule')
    op.drop_table('coveragerule')
    op.drop_index(op.f('ix_contact_name'), table_name='contact')
    op.drop_index(op.f('ix_contact_business_id'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_businessmodule_module_key'), table_name='businessmodule')
    op.drop_index(op.f('ix_businessmodule_business_id'), table_name='businessmodule')
    op.drop_table('businessmodule')
    op.drop_index(op.f('ix_business_name'), table_name='business')
    op.drop_table('business')
    op.drop_index(op.f('ix_billline_business_id'), table_name='billline')
    op.drop_index(op.f('ix_billline_bill_id'), table_name='billline')
    op.drop_index(op.f('ix_billline_account_id'), table_name='billline')
    op.drop_table('billline')
    op.drop_index(op.f('ix_bill_vendor_id'), table_name='bill')
    op.drop_index(op.f('ix_bill_business_id'), table_name='bill')
    op.drop_table('bill')
    op.drop_index(op.f('ix_availabilityrequest_user_id'), table_name='availabilityrequest')
    op.drop_index(op.f('ix_availabilityrequest_employee_id'), table_name='availabilityrequest')
    op.drop_index(op.f('ix_availabilityrequest_business_id'), table_name='availabilityrequest')
    op.drop_table('availabilityrequest')
    op.drop_index(op.f('ix_auditevent_user_id'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_business_id'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_action'), table_name='auditevent')
    op.drop_table('auditevent')
    op.drop_index(op.f('ix_assistantthread_user_id'), table_name='assistantthread')
    op.drop_index(op.f('ix_assistantthread_business_id'), table_name='assistantthread')
    op.drop_table('assistantthread')
    op.drop_index(op.f('ix_assistantmessage_user_id'), table_name='assistantmessage')
    op.drop_index(op.f('ix_assistantmessage_thread_id'), table_name='assistantmessage')
    op.drop_index(op.f('ix_assistantmessage_business_id'), table_name='assistantmessage')
    op.drop_table('assistantmessage')
    op.drop_index(op.f('ix_assistantmemory_user_id'), table_name='assistantmemory')
    op.drop_index(op.f('ix_assistantmemory_business_id'), table_name='assistantmemory')
    op.drop_table('assistantmemory')
    # ### end Alembic commands ###
